name: Banks in India Extractor - CI

on:
  workflow_dispatch: # To trigger the action from REST API
  pull_request:
    branches:
      - '**'  # Runs on every branch

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required dorny/paths-filter
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          src:
            - 'src/jobs/vatti/banks-in-india-extractor.js'

  extract-banks-in-india-ci:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    environment: development
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Extract
        run: npm run vatti:extract-banks-in-india
