name: Currency List Extractor

on:
  # Manual trigger
  workflow_dispatch:
  # At 10:30 AM UTC (04:00 PM IST) on every Friday.
  schedule:
    - cron: "30 10 * * 5"

jobs:
  extract-currency-list:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm" # Cache node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Extract
        run: npm run palan:extract-currency-list -- --save
        env:
          CURRENCY_LIST_JSON_BLOB: ${{ secrets.CURRENCY_LIST_JSON_BLOB }}
          CURRENCY_LIST_DATA_SOURCE_URL: ${{ vars.CURRENCY_LIST_DATA_SOURCE_URL }}
