name: IBJA Gold Rates Extractor - CI

on:
  workflow_dispatch: # To trigger the action from REST API
  pull_request:
    branches:
      - "**" # Runs on every branch

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required dorny/paths-filter
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/jobs/vatti/ibja-gold-rates-extractor.js'

  extract-ibja-gold-rates-ci:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    environment: development
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm" # Cache node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Extract
        run: npm run vatti:extract-ibja-gold-rates
        env:
          IBJA_GOLD_RATES_DATA_SOURCE_URL: ${{ vars.IBJA_GOLD_RATES_DATA_SOURCE_URL }}
