name: RBI Policy Rates Extractor

on:
  # Manual trigger
  workflow_dispatch:
  # At 10:30 AM UTC (04:00 PM IST) on 15th of every month.
  schedule:
    - cron: "30 10 15 * *"

jobs:
  extract-rbi-policy-rates:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm' # Cache node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Extract
        run: npm run vatti:extract-rbi-policy-rates -- --save
        env:
          RBI_POLICY_RATES_JSON_BLOB: ${{ secrets.RBI_POLICY_RATES_JSON_BLOB }}
