name: IBJA Gold Rates Extractor

on:
  # Manual trigger
  workflow_dispatch:
  # At 04:00 AM UTC (09:30 AM IST) and 07:00 AM UTC (12:30 PM IST) on Monday to Friday.
  schedule:
    - cron: "0 4,7 * * 1-5"

jobs:
  extract-ibja-gold-rates:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm' # Cache node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Extract
        run: npm run vatti:extract-ibja-gold-rates -- --save
        env:
          IBJA_GOLD_RATES_JSON_BLOB: ${{ secrets.IBJA_GOLD_RATES_JSON_BLOB }}
