name: Stock Portfolio Summary Notifier

on:
  workflow_dispatch: # To trigger the action from REST API

jobs:
  notify-stock-portfolio-summary:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm' # Cache node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Notify
        run: npm run pangu:notify-stock-portfolio-summary
        env:
          DB_URL: ${{ secrets.DB_URL }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          HTML_TO_IMAGE_USER_ID: ${{ secrets.HTML_TO_IMAGE_USER_ID }}
          HTML_TO_IMAGE_API_KEY: ${{ secrets.HTML_TO_IMAGE_API_KEY }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_COLLECTION: ${{ vars.DB_COLLECTION }}
          NIFTY_FIFTY_DATA_API_URL: ${{ vars.NIFTY_FIFTY_DATA_API_URL }}
          STOCK_DATA_API_URL: ${{ vars.STOCK_DATA_API_URL }}
          HTML_TO_IMAGE_API_URL: ${{ vars.HTML_TO_IMAGE_API_URL }}
